// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'models/company_model.dart';
import 'models/customer_model.dart';
import 'models/product_model.dart';
import 'models/product_provider_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 5463579012935817184),
      name: 'CompanyModel',
      lastPropertyId: const IdUid(1, 4703023321913533326),
      flags: 2,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4703023321913533326),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(name: 'costumers', srcEntity: 'Customer', srcField: ''),
        ModelBacklink(name: 'products', srcEntity: 'Product', srcField: ''),
        ModelBacklink(
            name: 'providers', srcEntity: 'ProductProvider', srcField: '')
      ]),
  ModelEntity(
      id: const IdUid(2, 8820484367074485462),
      name: 'Customer',
      lastPropertyId: const IdUid(9, 5162368302528333667),
      flags: 2,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8243299610050040476),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4352879079295237305),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7504789888863389416),
            name: 'cpf',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8875682626921946174),
            name: 'address',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8529808974134033250),
            name: 'phoneNumber1',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 7675207072557326770),
            name: 'phoneNumber2',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 3899266281975842049),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 2650791592218272155),
            name: 'observations',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 5162368302528333667),
            name: 'dbModelId',
            type: 11,
            flags: 520,
            indexId: const IdUid(1, 7499422510775991034),
            relationTarget: 'CompanyModel')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 4904316099294591961),
      name: 'Product',
      lastPropertyId: const IdUid(12, 7866254947640694500),
      flags: 2,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 850851500710235096),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7234586053937796899),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4803318705932067431),
            name: 'cod',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7489684483166139415),
            name: 'productProviderDocument',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 6123993166957582053),
            name: 'costValue',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 4664858484599130079),
            name: 'saleValue',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 9219642014939235897),
            name: 'brand',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 6733111936576073739),
            name: 'categoryName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 1654787533216116379),
            name: 'unitMeasurement',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 5525610289544025141),
            name: 'minQuantity',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 8063275579816512806),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 7866254947640694500),
            name: 'dbModelId',
            type: 11,
            flags: 520,
            indexId: const IdUid(2, 7071377280175833286),
            relationTarget: 'CompanyModel')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 8238452823228411886),
      name: 'ProductProvider',
      lastPropertyId: const IdUid(9, 7359975911946653570),
      flags: 2,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5478845100405282780),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 6494061209052479616),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5213024281811599873),
            name: 'document',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4721879238675706777),
            name: 'phoneNumber1',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7259875069780323998),
            name: 'phoneNumber2',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8748167960426978788),
            name: 'address',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 5304039918728791604),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 6005183947765977027),
            name: 'observations',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 7359975911946653570),
            name: 'dbModelId',
            type: 11,
            flags: 520,
            indexId: const IdUid(3, 7820354820842491682),
            relationTarget: 'CompanyModel')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(4, 8238452823228411886),
      lastIndexId: const IdUid(3, 7820354820842491682),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    CompanyModel: EntityDefinition<CompanyModel>(
        model: _entities[0],
        toOneRelations: (CompanyModel object) => [],
        toManyRelations: (CompanyModel object) => {
              RelInfo<Customer>.toOneBacklink(
                      9, object.id, (Customer srcObject) => srcObject.dbModel):
                  object.costumers,
              RelInfo<Product>.toOneBacklink(
                      12, object.id, (Product srcObject) => srcObject.dbModel):
                  object.products,
              RelInfo<ProductProvider>.toOneBacklink(9, object.id,
                      (ProductProvider srcObject) => srcObject.dbModel):
                  object.providers
            },
        getId: (CompanyModel object) => object.id,
        setId: (CompanyModel object, int id) {
          object.id = id;
        },
        objectToFB: (CompanyModel object, fb.Builder fbb) {
          fbb.startTable(2);
          fbb.addInt64(0, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = CompanyModel(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));
          InternalToManyAccess.setRelInfo(
              object.costumers,
              store,
              RelInfo<Customer>.toOneBacklink(
                  9, object.id, (Customer srcObject) => srcObject.dbModel),
              store.box<CompanyModel>());
          InternalToManyAccess.setRelInfo(
              object.products,
              store,
              RelInfo<Product>.toOneBacklink(
                  12, object.id, (Product srcObject) => srcObject.dbModel),
              store.box<CompanyModel>());
          InternalToManyAccess.setRelInfo(
              object.providers,
              store,
              RelInfo<ProductProvider>.toOneBacklink(9, object.id,
                  (ProductProvider srcObject) => srcObject.dbModel),
              store.box<CompanyModel>());
          return object;
        }),
    Customer: EntityDefinition<Customer>(
        model: _entities[1],
        toOneRelations: (Customer object) => [object.dbModel],
        toManyRelations: (Customer object) => {},
        getId: (Customer object) => object.id,
        setId: (Customer object, int id) {
          object.id = id;
        },
        objectToFB: (Customer object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final cpfOffset =
              object.cpf == null ? null : fbb.writeString(object.cpf!);
          final addressOffset =
              object.address == null ? null : fbb.writeString(object.address!);
          final phoneNumber1Offset = object.phoneNumber1 == null
              ? null
              : fbb.writeString(object.phoneNumber1!);
          final phoneNumber2Offset = object.phoneNumber2 == null
              ? null
              : fbb.writeString(object.phoneNumber2!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final observationsOffset = object.observations == null
              ? null
              : fbb.writeString(object.observations!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, cpfOffset);
          fbb.addOffset(3, addressOffset);
          fbb.addOffset(4, phoneNumber1Offset);
          fbb.addOffset(5, phoneNumber2Offset);
          fbb.addOffset(6, emailOffset);
          fbb.addOffset(7, observationsOffset);
          fbb.addInt64(8, object.dbModel.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Customer(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              cpf: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              address: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              phoneNumber1: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              phoneNumber2: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              email: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              observations: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18));
          object.dbModel.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.dbModel.attach(store);
          return object;
        }),
    Product: EntityDefinition<Product>(
        model: _entities[2],
        toOneRelations: (Product object) => [object.dbModel],
        toManyRelations: (Product object) => {},
        getId: (Product object) => object.id,
        setId: (Product object, int id) {
          object.id = id;
        },
        objectToFB: (Product object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final codOffset = fbb.writeString(object.cod);
          final productProviderDocumentOffset =
              fbb.writeString(object.productProviderDocument);
          final brandOffset = fbb.writeString(object.brand);
          final categoryNameOffset = fbb.writeString(object.categoryName);
          final unitMeasurementOffset = fbb.writeString(object.unitMeasurement);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(13);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, codOffset);
          fbb.addOffset(3, productProviderDocumentOffset);
          fbb.addFloat64(4, object.costValue);
          fbb.addFloat64(5, object.saleValue);
          fbb.addOffset(6, brandOffset);
          fbb.addOffset(7, categoryNameOffset);
          fbb.addOffset(8, unitMeasurementOffset);
          fbb.addInt64(9, object.minQuantity);
          fbb.addOffset(10, descriptionOffset);
          fbb.addInt64(11, object.dbModel.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Product(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              cod: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              productProviderDocument:
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGet(buffer, rootOffset, 10, ''),
              brand: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, ''),
              categoryName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, ''),
              unitMeasurement: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 20, ''),
              costValue:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0),
              saleValue:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0),
              minQuantity: const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
              description: const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 24, ''));
          object.dbModel.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          object.dbModel.attach(store);
          return object;
        }),
    ProductProvider: EntityDefinition<ProductProvider>(
        model: _entities[3],
        toOneRelations: (ProductProvider object) => [object.dbModel],
        toManyRelations: (ProductProvider object) => {},
        getId: (ProductProvider object) => object.id,
        setId: (ProductProvider object, int id) {
          object.id = id;
        },
        objectToFB: (ProductProvider object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final documentOffset = object.document == null
              ? null
              : fbb.writeString(object.document!);
          final phoneNumber1Offset = object.phoneNumber1 == null
              ? null
              : fbb.writeString(object.phoneNumber1!);
          final phoneNumber2Offset = object.phoneNumber2 == null
              ? null
              : fbb.writeString(object.phoneNumber2!);
          final addressOffset =
              object.address == null ? null : fbb.writeString(object.address!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final observationsOffset = object.observations == null
              ? null
              : fbb.writeString(object.observations!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, documentOffset);
          fbb.addOffset(3, phoneNumber1Offset);
          fbb.addOffset(4, phoneNumber2Offset);
          fbb.addOffset(5, addressOffset);
          fbb.addOffset(6, emailOffset);
          fbb.addOffset(7, observationsOffset);
          fbb.addInt64(8, object.dbModel.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ProductProvider(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              document: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              phoneNumber1: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              phoneNumber2: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              address: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              email: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              observations: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18));
          object.dbModel.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.dbModel.attach(store);
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [CompanyModel] entity fields to define ObjectBox queries.
class CompanyModel_ {
  /// see [CompanyModel.id]
  static final id =
      QueryIntegerProperty<CompanyModel>(_entities[0].properties[0]);
}

/// [Customer] entity fields to define ObjectBox queries.
class Customer_ {
  /// see [Customer.id]
  static final id = QueryIntegerProperty<Customer>(_entities[1].properties[0]);

  /// see [Customer.name]
  static final name = QueryStringProperty<Customer>(_entities[1].properties[1]);

  /// see [Customer.cpf]
  static final cpf = QueryStringProperty<Customer>(_entities[1].properties[2]);

  /// see [Customer.address]
  static final address =
      QueryStringProperty<Customer>(_entities[1].properties[3]);

  /// see [Customer.phoneNumber1]
  static final phoneNumber1 =
      QueryStringProperty<Customer>(_entities[1].properties[4]);

  /// see [Customer.phoneNumber2]
  static final phoneNumber2 =
      QueryStringProperty<Customer>(_entities[1].properties[5]);

  /// see [Customer.email]
  static final email =
      QueryStringProperty<Customer>(_entities[1].properties[6]);

  /// see [Customer.observations]
  static final observations =
      QueryStringProperty<Customer>(_entities[1].properties[7]);

  /// see [Customer.dbModel]
  static final dbModel =
      QueryRelationToOne<Customer, CompanyModel>(_entities[1].properties[8]);
}

/// [Product] entity fields to define ObjectBox queries.
class Product_ {
  /// see [Product.id]
  static final id = QueryIntegerProperty<Product>(_entities[2].properties[0]);

  /// see [Product.name]
  static final name = QueryStringProperty<Product>(_entities[2].properties[1]);

  /// see [Product.cod]
  static final cod = QueryStringProperty<Product>(_entities[2].properties[2]);

  /// see [Product.productProviderDocument]
  static final productProviderDocument =
      QueryStringProperty<Product>(_entities[2].properties[3]);

  /// see [Product.costValue]
  static final costValue =
      QueryDoubleProperty<Product>(_entities[2].properties[4]);

  /// see [Product.saleValue]
  static final saleValue =
      QueryDoubleProperty<Product>(_entities[2].properties[5]);

  /// see [Product.brand]
  static final brand = QueryStringProperty<Product>(_entities[2].properties[6]);

  /// see [Product.categoryName]
  static final categoryName =
      QueryStringProperty<Product>(_entities[2].properties[7]);

  /// see [Product.unitMeasurement]
  static final unitMeasurement =
      QueryStringProperty<Product>(_entities[2].properties[8]);

  /// see [Product.minQuantity]
  static final minQuantity =
      QueryIntegerProperty<Product>(_entities[2].properties[9]);

  /// see [Product.description]
  static final description =
      QueryStringProperty<Product>(_entities[2].properties[10]);

  /// see [Product.dbModel]
  static final dbModel =
      QueryRelationToOne<Product, CompanyModel>(_entities[2].properties[11]);
}

/// [ProductProvider] entity fields to define ObjectBox queries.
class ProductProvider_ {
  /// see [ProductProvider.id]
  static final id =
      QueryIntegerProperty<ProductProvider>(_entities[3].properties[0]);

  /// see [ProductProvider.name]
  static final name =
      QueryStringProperty<ProductProvider>(_entities[3].properties[1]);

  /// see [ProductProvider.document]
  static final document =
      QueryStringProperty<ProductProvider>(_entities[3].properties[2]);

  /// see [ProductProvider.phoneNumber1]
  static final phoneNumber1 =
      QueryStringProperty<ProductProvider>(_entities[3].properties[3]);

  /// see [ProductProvider.phoneNumber2]
  static final phoneNumber2 =
      QueryStringProperty<ProductProvider>(_entities[3].properties[4]);

  /// see [ProductProvider.address]
  static final address =
      QueryStringProperty<ProductProvider>(_entities[3].properties[5]);

  /// see [ProductProvider.email]
  static final email =
      QueryStringProperty<ProductProvider>(_entities[3].properties[6]);

  /// see [ProductProvider.observations]
  static final observations =
      QueryStringProperty<ProductProvider>(_entities[3].properties[7]);

  /// see [ProductProvider.dbModel]
  static final dbModel = QueryRelationToOne<ProductProvider, CompanyModel>(
      _entities[3].properties[8]);
}
